# macOS Tahoe Liquid Glass
foreground            #C9D1D9
background            #1C1E24
selection_foreground  #1C1E24
selection_background  #C9D1D9

# Transparent "Liquid Glass" effect
background_opacity         0.75
dynamic_background_opacity yes

# Tahoe ANSI — Normal (0-7)
color0  #1C1E24
color1  #ED5F5D
color2  #79B757
color3  #D29922
color4  #0088FF
color5  #BC8CFF
color6  #048ABF
color7  #C9D1D9

# Tahoe ANSI — Bright (8-15)
color8  #8B949E
color9  #ED5F5D
color10 #79B757
color11 #E9873A
color12 #0088FF
color13 #FF6489
color14 #048ABF
color15 #FFFFFF

# Window Padding
window_padding_width 15
