# Base16 macOS Tahoe Night
foreground            #C9D1D9
background            #0D1117
selection_foreground  #0D1117
selection_background  #C9D1D9

# Transparent "Liquid Glass" effect
background_opacity         0.75
dynamic_background_opacity yes

# The Tahoe Pink and Blue accents
color12  #0455BF
color14  #048ABF
color13  #FF6489

# Typography for matte screens
font_family      Inter
font_size        11.5
bold_font        auto
italic_font      auto
disable_ligatures never

# Window Padding
window_padding_width 15
