# vim:ft=kitty

# The basic colors
foreground              #FFFFFF
background              #073642
selection_foreground    #073642
selection_background    #FFFFFF

# Cursor colors
cursor                  #FDF6E3
cursor_text_color       background

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #073642
active_tab_background   #268BD2
inactive_tab_foreground #FDF6E3
inactive_tab_background #073642

# The 16 terminal colors
# black
color0 #586E75
color8 #657B83

# red
color1 #DC322F
color9 #F6524F

# green
color2  #859900
color10 #BAFB00

# yellow
color3  #B58900
color11 #FFC100

# blue
color4  #268BD2
color12 #49AEF5

# magenta
color5  #D33682
color13 #F255A1

# cyan
color6  #2AA198
color14 #29EEDF

# white
color7  #EEE8D5
color15 #FDF6E3
