exec-once=/usr/bin/fcitx5 -d
exec-once=awww-daemon
exec-once=udiskie -s
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
# exec-once=gnome-keyring-daemon --replace --components=secrets,ssh,pkcs11
exec-once=~/.config/quickshell/scripts/idle.sh
exec-once=systemctl --user start quickshell.service
