# Window effect
blur=1
blur_layer=1
blur_optimized=1
blur_params_num_passes = 3
blur_params_radius = 8
blur_params_noise = 0.02
blur_params_brightness = 0.9
blur_params_contrast = 0.9
blur_params_saturation = 1.2

shadows = 1
layer_shadows = 0 
shadow_only_floating = 1
shadows_size = 10
shadows_blur = 15
shadows_position_x = 0
shadows_position_y = 0
shadowscolor= 0x000000ff

border_radius=12
no_radius_when_single=0
focused_opacity=0.95
unfocused_opacity=0.75

# Appearance
gappih=15
gappiv=5
gappoh=10
gappov=10
scratchpad_width_ratio=0.8
scratchpad_height_ratio=0.9
borderpx=2
rootcolor=0x0d1117ff
bordercolor=x0d1117ff
focuscolor=0xff6489ff
maximizescreencolor=0x00ca4eff
urgentcolor=0xff605cff
scratchpadcolor=0x048abfff
globalcolor=x0d1117ff
overlaycolor=0xd9d2adff
