# window rules
windowrule=tags:1,appid:zen
windowrule=unfocused_opacity:0.75,appid:zen

windowrule=tags:1,appid:brave-browser
windowrule=focused_opacity:1.0,appid:brave-browser
windowrule=unfocused_opacity:0.75,appid:brave-browser

windowrule=tags:1,appid:helium
windowrule=focused_opacity:1.0,appid:helium
windowrule=unfocused_opacity:0.75,appid:helium

windowrule=tags:1,appid:vivaldi-stable
windowrule=focused_opacity:1.0,appid:vivaldi-stable
windowrule=unfocused_opacity:0.75,appid:vivaldi-stable

windowrule=tags:2,appid:kitty
windowrule=focused_opacity:0.95,appid:kitty
windowrule=unfocused_opacity:0.75,appid:kitty

windowrule=tags:3,appid:thunar
windowrule=unfocused_opacity:0.75,appid:thunar

# layer rules
layerrule=animation_type_open:zoom,layer_name:rofi
layerrule=animation_type_close:zoom,layer_name:rofi
layerrule=noblur:1,layer_name:waybar
