# window rules
windowrule=isfloating:1,title:Rename.*
windowrule=isfloating:1,title:File.*
windowrule=isfloating:1,minsize:800x600,title:*.wants to save
windowrule=isfloating:1,appid:io.ente.auth
windowrule=isnoradius:1,appid:rofi

# assign tags
windowrule=tags:1,appid:brave-origin

windowrule=tags:1,appid:helium

windowrule=tags:2,appid:kitty
windowrule=tags:2,appid:org.wezfurlong.wezterm

windowrule=tags:3,appid:org.gnome.Nautilus

# layer rules
# rofi
layerrule=animation_type_open:zoom,layer_name:rofi
layerrule=animation_type_close:zoom,layer_name:rofi
layerrule=noshadow:1,layer_name:rofi

# waybar
# layerrule=noblur:1,layer_name:waybar
layerrule=noshadow:1,layer_name:waybar

# swayosd
layerrule=noblur:1,layer_name:swayosd
layerrule=noshadow:1,layer_name:swayosd
