#!/usr/bin/env bash
set -euo pipefail

# The external GTK/icon/Kvantum repositories do not ship terminal companions.
# Keep those small, deterministic assets beside the Quickshell style logic so
# a fresh UI-suite install and a later style switch cannot select missing files.

script_dir=$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
kitty_dir="$HOME/.config/kitty"
starship_dir="$HOME/.config/starship"
btop_dir="$HOME/.config/btop/themes"

mkdir -p -- "$kitty_dir" "$starship_dir" "$btop_dir"

write_starship() {
  local style_name=$1
  local mode=$2
  local foreground accent branch muted success error

  case "$style_name:$mode" in
    nothing:light)
      foreground="#1a1a1a"
      accent="#d71920"
      branch="#5f6060"
      muted="#616161"
      success="#356a2f"
      error="#d71920"
      ;;
    nothing:dark)
      foreground="#f2f2f0"
      accent="#d71920"
      branch="#b8b8b5"
      muted="#b8b8b5"
      success="#9bd88d"
      error="#d71920"
      ;;
    ghost:light)
      foreground="#10201f"
      accent="#006d67"
      branch="#875400"
      muted="#4f6260"
      success="#287a3a"
      error="#b3261e"
      ;;
    ghost:dark)
      foreground="#cdeeea"
      accent="#57d9cc"
      branch="#e0a94a"
      muted="#5f7f7a"
      success="#8fe38a"
      error="#e0625a"
      ;;
    *)
      printf 'Unsupported fixed terminal style: %s %s\n' "$style_name" "$mode" >&2
      return 2
      ;;
  esac

  local output="$starship_dir/$style_name-$mode.toml"
  [[ -f "$output" ]] && return 0

  local temporary
  temporary=$(mktemp "${output}.tmp.XXXXXX")
  if ! cat >"$temporary" <<EOF
# Static $style_name Starship prompt — $mode
# Generated by ~/.config/quickshell/scripts/ensure-style-terminal-assets.sh
# Palette roles mirror config/Colors.qml and the matching fixed Kitty theme.
add_newline = false
format = "\$directory\$git_branch\$git_status\$cmd_duration\$character"

[directory]
style = "bold $foreground"
format = "[\$path](\$style) "
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = "git:"
style = "$branch"
format = "[\$symbol\$branch](\$style) "

[git_status]
style = "$branch"
format = "[\$all_status\$ahead_behind](\$style) "

[cmd_duration]
min_time = 2_000
style = "$muted"
format = "[\$duration](\$style) "

[character]
success_symbol = "[❯](bold $success)"
error_symbol = "[❯](bold $error)"
vimcmd_symbol = "[❮](bold $accent)"
EOF
  then
    rm -f -- "$temporary"
    return 1
  fi
  mv -f -- "$temporary" "$output"
}

write_ghost_btop() {
  local output="$btop_dir/ghost.theme"
  [[ -f "$output" ]] && return 0

  local temporary
  temporary=$(mktemp "${output}.tmp.XXXXXX")
  if ! cat >"$temporary" <<'EOF'
# GHOST (Section 9) theme for btop.
# Same fixed token palette as kitty/ghost-dark.conf and config/Colors.qml.
# This is deliberately static: do not route it through Matugen.

theme[main_bg]="#05080a"
theme[main_fg]="#cdeeea"
theme[title]="#cdeeea"
theme[hi_fg]="#57d9cc"
theme[selected_bg]="#12191d"
theme[selected_fg]="#78dcd0"
theme[inactive_fg]="#678984"
theme[graph_text]="#cdeeea"
theme[meter_bg]="#12191d"
theme[proc_misc]="#8fe38a"

theme[cpu_box]="#57d9cc"
theme[mem_box]="#8fe38a"
theme[net_box]="#e0a94a"
theme[proc_box]="#57d9cc"
theme[div_line]="#246a63"

theme[temp_start]="#8fe38a"
theme[temp_mid]="#e0a94a"
theme[temp_end]="#e0625a"

theme[cpu_start]="#246a63"
theme[cpu_mid]="#57d9cc"
theme[cpu_end]="#78dcd0"

theme[free_start]="#8fe38a"
theme[free_mid]="#57d9cc"
theme[free_end]="#246a63"

theme[cached_start]="#57d9cc"
theme[cached_mid]="#2f6f68"
theme[cached_end]="#12191d"

theme[available_start]="#e0a94a"
theme[available_mid]="#e0625a"
theme[available_end]="#e0625a"

theme[used_start]="#8fe38a"
theme[used_mid]="#57d9cc"
theme[used_end]="#78dcd0"

theme[download_start]="#e0a94a"
theme[download_mid]="#e0625a"
theme[download_end]="#e0625a"

theme[upload_start]="#8fe38a"
theme[upload_mid]="#57d9cc"
theme[upload_end]="#78dcd0"

theme[process_start]="#57d9cc"
theme[process_mid]="#78dcd0"
theme[process_end]="#cdeeea"
EOF
  then
    rm -f -- "$temporary"
    return 1
  fi
  mv -f -- "$temporary" "$output"
}

for fixed_style in nothing ghost; do
  write_starship "$fixed_style" light
  write_starship "$fixed_style" dark
done
write_ghost_btop

