#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 1 || $# -gt 3 ]]; then
  printf 'Usage: %s <light|dark> [kitty output path] [starship output path]\n' "$0" >&2
  exit 2
fi

mode=$1
if [[ "$mode" != "light" && "$mode" != "dark" ]]; then
  printf 'Invalid mode: %s\n' "$mode" >&2
  exit 2
fi

kitty_dir="$HOME/.config/kitty"
starship_dir="$HOME/.config/starship"
kitty_output_path=${2:-"$kitty_dir/neo-brutalism-matugen-$mode.conf"}
starship_output_path=${3:-"$starship_dir/neo-brutalism-matugen-$mode.toml"}
palette_file="$HOME/.cache/matugen/current_palette.json"

if [[ "$mode" == "light" ]]; then
  fallback_background="#fff8f7"
  fallback_foreground="#24191b"
  fallback_surface_container="#fee9ec"
  fallback_surface_container_high="#f9e3e6"
  fallback_primary="#006684"
  fallback_on_primary="#ffffff"
  fallback_primary_container="#bee9ff"
  fallback_on_primary_container="#001f2a"
  fallback_secondary="#825245"
  fallback_secondary_container="#ffdbd1"
  fallback_tertiary="#636121"
  fallback_tertiary_container="#eae698"
  fallback_error="#ba1a1a"
  fallback_on_surface_variant="#564146"
  fallback_outline="#8a7175"
else
  fallback_background="#1b1013"
  fallback_foreground="#f3dde0"
  fallback_surface_container="#281d1f"
  fallback_surface_container_high="#332729"
  fallback_primary="#80d1f5"
  fallback_on_primary="#003546"
  fallback_primary_container="#004d64"
  fallback_on_primary_container="#bee9ff"
  fallback_secondary="#f5b8a8"
  fallback_secondary_container="#663c30"
  fallback_tertiary="#ceca7e"
  fallback_tertiary_container="#4b4909"
  fallback_error="#ffb4ab"
  fallback_on_surface_variant="#ddbfc4"
  fallback_outline="#a58a8f"
fi

palette_role() {
  local role=$1
  local fallback=$2
  local value=""

  if [[ -f "$palette_file" ]] && command -v jq >/dev/null 2>&1; then
    value=$(jq -r --arg mode "$mode" --arg role "$role" \
      '."scheme-expressive"[$mode][$role] // empty' "$palette_file" 2>/dev/null || true)
  fi

  if [[ -n "$value" && "$value" != "null" ]]; then
    printf '%s' "$value"
  else
    printf '%s' "$fallback"
  fi
}

background=$(palette_role background "$fallback_background")
foreground=$(palette_role on_surface "$fallback_foreground")
surface_container=$(palette_role surface_container "$fallback_surface_container")
surface_container_high=$(palette_role surface_container_high "$fallback_surface_container_high")
primary=$(palette_role primary "$fallback_primary")
on_primary=$(palette_role on_primary "$fallback_on_primary")
primary_container=$(palette_role primary_container "$fallback_primary_container")
on_primary_container=$(palette_role on_primary_container "$fallback_on_primary_container")
secondary=$(palette_role secondary "$fallback_secondary")
secondary_container=$(palette_role secondary_container "$fallback_secondary_container")
tertiary=$(palette_role tertiary "$fallback_tertiary")
tertiary_container=$(palette_role tertiary_container "$fallback_tertiary_container")
error=$(palette_role error "$fallback_error")
on_surface_variant=$(palette_role on_surface_variant "$fallback_on_surface_variant")
outline=$(palette_role outline "$fallback_outline")

if [[ "$mode" == "light" ]]; then
  selection_background=$primary_container
  selection_foreground=$on_primary_container
  active_tab_background=$primary_container
  active_tab_foreground=$on_primary_container
else
  selection_background=$primary
  selection_foreground=$on_primary
  active_tab_background=$primary
  active_tab_foreground=$on_primary
fi

mkdir -p "$(dirname "$kitty_output_path")" "$(dirname "$starship_output_path")"
kitty_temporary_path=$(mktemp "$kitty_output_path.tmp.XXXXXX")
starship_temporary_path=$(mktemp "$starship_output_path.tmp.XXXXXX")
trap 'rm -f "$kitty_temporary_path" "$starship_temporary_path"' EXIT

cat > "$kitty_temporary_path" <<EOF
# Neo Brutalism Kitty theme — Matugen $mode
# Generated by ~/.config/quickshell/scripts/generate-neo-kitty-theme.sh
# Colors are the current wallpaper-derived Material 3 roles; Neo Brutalism's
# visual treatment is supplied by the surrounding desktop theme.

foreground            $foreground
background            $background
selection_foreground  $selection_foreground
selection_background  $selection_background

cursor                $primary
cursor_text_color     $on_primary

url_color             $primary

active_tab_foreground   $active_tab_foreground
active_tab_background   $active_tab_background
inactive_tab_foreground $on_surface_variant
inactive_tab_background $surface_container_high

background_opacity         1.0
dynamic_background_opacity yes

# ANSI — Normal (0-7)
# black=surface_container red=error green=tertiary yellow=primary
# blue=secondary magenta=tertiary_container cyan=secondary_container
color0  $surface_container
color1  $error
color2  $tertiary
color3  $primary
color4  $secondary
color5  $tertiary_container
color6  $secondary_container
color7  $on_surface_variant

# ANSI — Bright (8-15)
color8  $outline
color9  $error
color10 $tertiary
color11 $primary_container
color12 $secondary
color13 $tertiary_container
color14 $secondary_container
color15 $foreground
EOF

cat > "$starship_temporary_path" <<EOF
# Neo Brutalism Starship prompt — Matugen $mode
# Generated by ~/.config/quickshell/scripts/generate-neo-kitty-theme.sh
# Colors are the current wallpaper-derived Material 3 roles; the surrounding
# desktop theme supplies Neo Brutalism's geometry and typography.

format = """
\$username\\
\$hostname\\
\$directory\\
\$git_branch\\
\$git_state\\
\$git_status\\
\$fill\\
\$cmd_duration\\
\$line_break\\
\$python\\
\$lua\\
\$c\\
\$rust\\
\$perl\\
\$php\\
\$ruby\\
\$character"""

[fill]
symbol = ' '

[directory]
read_only = " 󰌾"
style = "$foreground"

[character]
success_symbol = "[❯]($tertiary)"
error_symbol = "[❯]($error)"
vimcmd_symbol = "[❮]($secondary)"

[git_branch]
format = "[\$branch](\$style)"
style = "$secondary"

[git_status]
format = "[[(*\$conflicted\$untracked\$modified\$staged\$renamed\$deleted)](218) (\$ahead_behind\$stashed)](\$style)"
style = "$foreground"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\\([\$state( \$progress_current/\$progress_total)](\$style)\\) '
style = "$primary"

[cmd_duration]
format = " [\$duration](\$style) "
style = "$primary"

[time]
disabled = false
time_format = "%T"
format = '\$time'

[c]
symbol = '󰙱 '
style = "$primary"

[lua]
symbol = "󰢱 "
style = "$primary"

[nodejs]
symbol = "⬢ "
style = "$primary"

[perl]
symbol = " "
style = "$primary"

[php]
symbol = " "
style = "$primary"

[python]
symbol = " "
style = "$primary"

[ruby]
symbol = " "
style = "$primary"

[rust]
symbol = " "
style = "$primary"
EOF

mv -f "$kitty_temporary_path" "$kitty_output_path"
mv -f "$starship_temporary_path" "$starship_output_path"
trap - EXIT
