$bg0 = rgba(0D1117ff)
$bg1 = rgba(161B22ff)

$fg0 = rgba(C9D1D9ff)
$fg1 = rgba(F0F6FCff)

$red = rgba(FF605Cff)
$green = rgba(00CA4Eff)
$yellow = rgba(E3B341ff)
$blue = rgba(0455BFff)
$magenta = rgba(7D55C7ff)
$cyan = rgba(048ABFff)
$orange = rgba(FFBD44ff)
$pink = rgba(FF6489ff)
