plugin {
  hyprexpo {
    columns = 3
    gap_size = 5
    bg_col = rgb(1e1e2e)
    workspace_method = center current # [center/first] [workspace] e.g. first 1 or center m+1
    gesture_distance = 300 # how far is the "max" for the gesture
    hyprexpo-gesture = 3, vertical, expo
  }
  hyprscrolling {
    column_width = 0.5
    fullscreen_on_one_column = false
  }
}
