source = ~/.config/hypr/themes/catppuccin-mocha.conf

plugin {
  hyprexpo {
    columns = 3
    gap_size = 5
    bg_col = $bg0
    workspace_method = center current # [center/first] [workspace] e.g. first 1 or center m+1
    gesture_distance = 300 # how far is the "max" for the gesture
    hyprexpo-gesture = 3, vertical, expo
  }
  hyprscrolling {
    column_width = 0.5
    fullscreen_on_one_column = true
  }
  borders-plus-plus {
    add_borders = 1 # 0 - 9
    # you can add up to 9 borders
    col.border_1 = $bg0
    col.border_2 = $blue
    # -1 means "default" as in the one defined in general:border_size
    border_size_1 = 5
    border_size_2 = -1
    # makes outer edges match rounding of the parent. Turn on / off to better understand. Default = on.
    natural_rounding = no
  }
}
