# Basics
windowrule {
  name = suppress-maximize-events
  match:class = .*
  suppress_event = maximize
}

windowrule {
  name = fix-xwayland-drags
  match:class = ^$
  match:title = ^$
  match:xwayland = true
  match:float = true
  match:fullscreen = false
  match:pin = false

  no_focus = true
  animation = false
}

windowrule {
    name = browser-popups
    match:class =  ^(firefox|zen|brave-browser|helium|vivaldi-stable)$
    match:title = ^$
    match:float = true
    animation = false
  }

windowrule {
  name = move-hyprland-run
  match:class = hyprland-run
  move = 20 monitor_h-120
  float = yes
}

# Floating Rules
windowrule {
  name = floating-rules
  float = on
  match:class = ^([Xx]dg-desktop-portal-gtk)$
}

windowrule {
    name = thunar-rename
    float = on
    match:class = ^(thunar)$
    match:title = ^(Rename.*)$
  }

windowrule {
  name = protonvpn
  float = on
  match:class = ^(protonvpn-app)$
  match:title = ^()$
}

windowrule {
  name = galculator
  float = on
  match:class = ^(galculator)$
}

windowrule {
    name = fcitx
    pseudo = on
  }

# Blur
layerrule {
  name = mako
  blur = on
  ignore_alpha = 0.2
  match:namespace = mako
}

layerrule {
  name = notifications
  blur = on
  ignore_alpha = 0.2
  match:namespace = notifications
}

layerrule {
  name = waybar
  blur = on
  match:namespace = waybar
  ignore_alpha = 0.2
}

layerrule {
  name = rofi
  blur = on
  ignore_alpha = 0
  match:namespace = rofi
}

layerrule {
  name = wlogout
  blur = on
  ignore_alpha = 0.01
  match:namespace = logout_dialog
}

layerrule {
  name = noctalia
  match:namespace = noctalia-background-.*$
  ignore_alpha = 0.5
  blur = true
  blur_popups = true
}

# Idle inhibit when playing videos
windowrule {
  name = inhibit-mpv
  idle_inhibit = focus
  match:class = ^(mpv)
}

windowrule {
  name = inhibit-fullscreen-browsers
  idle_inhibit = fullscreen
  match:class = ^(firefox)|^(brave)|^(zen)|^(helium)|^(vivaldi-stable)
}

# Fullscreen apps
# windowrule {
#   name = wlogout
#   fullscreen = on
#   match:class = ^(wlogout)
# }

# No amimation apps
windowrule {
  name = rofi
  animation = none
  match:class = ^([Rr]ofi)
}

# Context menu fixes
windowrule {
    name = context-menu
    match:class = REAPER
    float = on
    move = cursor 5px 15px
    min_size = 1 1
    stay_focused = on
    no_blur = on
}

# Assign apps to workspaces
windowrule {
  name = workspace1-browsers
  # opacity = 1.0 override 0.5 override
  workspace = 1
  match:class = ^(firefox)$|^(zen)$|^(brave-browser)$|^(helium)|^(vivaldi-stable)
}

windowrule {
  name = workspace2-terminals
  workspace = 2
  match:class = ^(kitty)$
}

windowrule {
  name = workspace3-filem
  workspace = 3
  match:class = ^(org.gnome.Nautilus)$
}

windowrule {
  name = workspace5-qbittorrent
  workspace = 5
  match:class = ^(org.qbittorrent.qBittorrent)$
}

# Smart gaps
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule = border_size 0, match:float 0, match:workspace w[tv1]
# windowrule = rounding 0, match:float 0, match:workspace w[tv1]
# windowrule = border_size 0, match:float 0, match:workspace f[1]
# windowrule = rounding 0, match:float 0, match:workspace f[1]
