hl.on("hyprland.start", function()
  hl.exec_cmd("dbus-update-activation-environment --systemd --all")
  hl.exec_cmd("systemctl --user import-environment QT_QPA_PLATFORMTHEME")
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("systemctl --user restart awww-daemon.service")
  hl.exec_cmd("systemctl --user restart quickshell.service")
  hl.exec_cmd('hypridle -c "$HOME/.config/hypr/hypridle.conf"')
  hl.exec_cmd("fcitx5 -d")
end)
