general {
    lock_cmd = pidoff hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
<<<<<<< HEAD
    # after_sleep_cmd = hyprctl dispatch dpms on
    after_sleep_cmd = wlopm --on \* inhibit_sleep = 3
=======
    after_sleep_cmd = hyprctl dispatch dpms on
>>>>>>> 5b26e3826b046dcb1f51e1094709b9deed30680c
    inhibit_sleep = 3
}

listener {
    timeout = 150
    on-timeout = sh -c 'if grep -q "Discharging" /sys/class/power_supply/BAT*/status; then brightnessctl set 30%; else brightnessctl set 100%; fi'
    on-resume = brightnessctl set 100%
}

listener {
<<<<<<< HEAD
    timeout = 300
=======
    timeout = 180
>>>>>>> 5b26e3826b046dcb1f51e1094709b9deed30680c
    on-timeout = loginctl lock-session
}

listener {
<<<<<<< HEAD
    timeout = 600
    # on-timeout = hyprctl dispatch dpms off
    # on-resume = hyprctl dispatch dpms on
    on-timeout = wlopm --off \*
    on-resume = wlopm --on \*
}

listener {
    timeout = 900
=======
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 360
>>>>>>> 5b26e3826b046dcb1f51e1094709b9deed30680c
    on-timeout = systemctl suspend
}
