format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$fill\
$cmd_duration\
$line_break\
$python\
$lua\
$c\
$rust\
$perl\
$php\
$ruby\
$character"""

[fill]
symbol = ' '

[directory]
read_only = " 󰌾"
style = "#3D3929"

[character]
success_symbol = "[❯](#3D3929)"
error_symbol = "[❯](#BD5D3A)"
vimcmd_symbol = "[❮](#8492A3)"

[git_branch]
format = "[$branch]($style)"
style = "#3D3929"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "#3D3929"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#3D3929"

[cmd_duration]
format = " [$duration]($style) "
style = "#3D3929"

[time]
disabled = false
time_format = "%T"
format = '$time'

[c]
symbol = '󰙱 '
style = "#3D3929"

[lua]
symbol = "󰢱 "
style = "#3D3929"

[nodejs]
symbol = "⬢ "
style = "#3D3929"

[perl]
symbol = " "
style = "#3D3929"

[php]
symbol = " "
style = "#3D3929"

[python]
symbol = " "
style = "#3D3929"

[ruby]
symbol = " "
style = "#3D3929"

[rust]
symbol = " "
style = "#3D3929"

