format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$fill\
$cmd_duration\
$line_break\
$python\
$lua\
$c\
$rust\
$perl\
$php\
$ruby\
$character"""

[fill]
symbol = ' '

[directory]
read_only = " 󰌾"
style = "#79d7c0"

[character]
success_symbol = "[❯](#79d7c0)"
error_symbol = "[❯](#ffb4ab)"
vimcmd_symbol = "[❮](#e0b9ee)"

[git_branch]
format = "[$branch]($style)"
style = "#cfc2d3"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "#e0b9ee"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#988d9d"

[cmd_duration]
format = " [$duration]($style) "
style = "#e0b9ee"

[time]
disabled = false
time_format = "%T"
format = '$time'

[c]
symbol = '󰙱 '

[lua]
symbol = "󰢱 "

[nodejs]
symbol = "⬢ "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

