# Generated by sync-terminal-theme.sh — do not edit directly
export STARSHIP_CONFIG="/home/mura/.config/starship/claude-light.toml"
# Claude.ai Optimized Light Theme — static, matches kitty claude-light.conf
export FZF_DEFAULT_OPTS=" \
--color=bg:#EFEEEB,fg:#615D52,hl:#D97757,fg+:#121212,bg+:#E3E3E2,hl+:#D97757,info:#2A77D5,prompt:#D97757,pointer:#D97757,marker:#2A77D5,spinner:#9B8178,header:#898781,border:#898781 \
"
