// Colors.qml  —  generated by matugen (expressive)
import QtQml
import QtQuick

QtObject {
  id: colors

  property int themePreference: 0
  property bool systemDark: false
  property bool darkMode: themePreference === 1 ? false : (themePreference === 2 ? true : systemDark)

  readonly property color l_bg: "#fff8f6"
  readonly property color l_surface: "#fff8f6"
  readonly property color l_surfaceDim: "#ecd5ce"
  readonly property color l_surfaceBright: "#fff8f6"
  readonly property color l_surfaceContainer: "#ffe9e3"
  readonly property color l_surfaceContainerHigh: "#fbe3dc"
  readonly property color l_surfaceContainerHighest: "#f5ded7"
  readonly property color l_surfaceVariant: "#fddbd1"
  readonly property color l_primary: "#3a5f98"
  readonly property color l_onPrimary: "#ffffff"
  readonly property color l_primaryContainer: "#d6e3ff"
  readonly property color l_onPrimaryContainer: "#001b3e"
  readonly property color l_secondary: "#5c6236"
  readonly property color l_onSecondary: "#ffffff"
  readonly property color l_secondaryContainer: "#e1e7b0"
  readonly property color l_onSecondaryContainer: "#1a1e00"
  readonly property color l_tertiary: "#44673b"
  readonly property color l_onTertiary: "#ffffff"
  readonly property color l_tertiaryContainer: "#c5eeb6"
  readonly property color l_onTertiaryContainer: "#012201"
  readonly property color l_error: "#ba1a1a"
  readonly property color l_onError: "#ffffff"
  readonly property color l_errorContainer: "#ffdad6"
  readonly property color l_onErrorContainer: "#410002"
  readonly property color l_onSurface: "#251915"
  readonly property color l_onSurfaceVariant: "#58423a"
  readonly property color l_outline: "#8c7169"
  readonly property color l_outlineVariant: "#dfc0b6"
  readonly property color l_shadow: "#000000"
  readonly property color l_scrim: "#000000"

  readonly property color d_bg: "#1c110d"
  readonly property color d_surface: "#1c110d"
  readonly property color d_surfaceDim: "#1c110d"
  readonly property color d_surfaceBright: "#443631"
  readonly property color d_surfaceContainer: "#291d19"
  readonly property color d_surfaceContainerHigh: "#342723"
  readonly property color d_surfaceContainerHighest: "#40322d"
  readonly property color d_surfaceVariant: "#58423a"
  readonly property color d_primary: "#a9c7ff"
  readonly property color d_onPrimary: "#003064"
  readonly property color d_primaryContainer: "#1f467e"
  readonly property color d_onPrimaryContainer: "#d6e3ff"
  readonly property color d_secondary: "#c5cb96"
  readonly property color d_onSecondary: "#2e330c"
  readonly property color d_secondaryContainer: "#454a21"
  readonly property color d_onSecondaryContainer: "#e1e7b0"
  readonly property color d_tertiary: "#a9d19c"
  readonly property color d_onTertiary: "#163711"
  readonly property color d_tertiaryContainer: "#2c4f26"
  readonly property color d_onTertiaryContainer: "#c5eeb6"
  readonly property color d_error: "#ffb4ab"
  readonly property color d_onError: "#690005"
  readonly property color d_errorContainer: "#93000a"
  readonly property color d_onErrorContainer: "#ffdad6"
  readonly property color d_onSurface: "#f5ded7"
  readonly property color d_onSurfaceVariant: "#dfc0b6"
  readonly property color d_outline: "#a78b81"
  readonly property color d_outlineVariant: "#58423a"
  readonly property color d_shadow: "#000000"
  readonly property color d_scrim: "#000000"

  property color bg: darkMode ? d_bg : l_bg
  property color surface: darkMode ? d_surface : l_surface
  property color surfaceDim: darkMode ? d_surfaceDim : l_surfaceDim
  property color surfaceBright: darkMode ? d_surfaceBright : l_surfaceBright
  property color surfaceContainer: darkMode ? d_surfaceContainer : l_surfaceContainer
  property color surfaceContainerHigh: darkMode ? d_surfaceContainerHigh : l_surfaceContainerHigh
  property color surfaceContainerHighest: darkMode ? d_surfaceContainerHighest : l_surfaceContainerHighest
  property color surfaceVariant: darkMode ? d_surfaceVariant : l_surfaceVariant
  property color primary: darkMode ? d_primary : l_primary
  property color fgPrimary: darkMode ? d_onPrimary : l_onPrimary
  property color primaryContainer: darkMode ? d_primaryContainer : l_primaryContainer
  property color fgPrimaryContainer: darkMode ? d_onPrimaryContainer : l_onPrimaryContainer
  property color secondary: darkMode ? d_secondary : l_secondary
  property color fgSecondary: darkMode ? d_onSecondary : l_onSecondary
  property color secondaryContainer: darkMode ? d_secondaryContainer : l_secondaryContainer
  property color fgSecondaryContainer: darkMode ? d_onSecondaryContainer : l_onSecondaryContainer
  property color tertiary: darkMode ? d_tertiary : l_tertiary
  property color fgTertiary: darkMode ? d_onTertiary : l_onTertiary
  property color tertiaryContainer: darkMode ? d_tertiaryContainer : l_tertiaryContainer
  property color fgTertiaryContainer: darkMode ? d_onTertiaryContainer : l_onTertiaryContainer
  property color error: darkMode ? d_error : l_error
  property color fgError: darkMode ? d_onError : l_onError
  property color errorContainer: darkMode ? d_errorContainer : l_errorContainer
  property color fgErrorContainer: darkMode ? d_onErrorContainer : l_onErrorContainer
  property color fgSurface: darkMode ? d_onSurface : l_onSurface
  property color fgSurfaceVariant: darkMode ? d_onSurfaceVariant : l_onSurfaceVariant
  property color outline: darkMode ? d_outline : l_outline
  property color outlineVariant: darkMode ? d_outlineVariant : l_outlineVariant
  property color shadow: darkMode ? d_shadow : l_shadow
  property color scrim: darkMode ? d_scrim : l_scrim
  property color hoverOverlay: darkMode ? Qt.rgba(1, 1, 1, 0.10) : Qt.rgba(0, 0, 0, 0.06)
  property color pressOverlay: darkMode ? Qt.rgba(1, 1, 1, 0.16) : Qt.rgba(0, 0, 0, 0.10)
}
