// Colors.qml  —  generated by matugen (expressive) + claude scheme
import QtQml
import QtQuick

QtObject {
  id: colors

  property int themePreference: 0
  property bool systemDark: false
  property bool darkMode: themePreference === 1 ? false : (themePreference === 2 ? true : systemDark)
  property string colorScheme: "matugen" // "matugen" | "claude"

  // Claude light palette (mapped from claude.ai / kitty colors)
  readonly property color cl_l_bg:                     "#EEECE2"
  readonly property color cl_l_surface:                "#EEECE2"
  readonly property color cl_l_surfaceDim:             "#E6E3D5"
  readonly property color cl_l_surfaceBright:          "#EEECE2"
  readonly property color cl_l_surfaceContainer:       "#E0DDD0"
  readonly property color cl_l_surfaceContainerHigh:   "#D8D5C8"
  readonly property color cl_l_surfaceContainerHighest:"#D0CEC2"
  readonly property color cl_l_surfaceVariant:         "#E6E3D5"
  readonly property color cl_l_primary:                "#BD5D3A"
  readonly property color cl_l_onPrimary:              "#FFFFFF"
  readonly property color cl_l_primaryContainer:       "#F5D5C8"
  readonly property color cl_l_onPrimaryContainer:     "#3D1A0A"
  readonly property color cl_l_secondary:              "#8492A3"
  readonly property color cl_l_onSecondary:            "#FFFFFF"
  readonly property color cl_l_secondaryContainer:     "#D8E0EB"
  readonly property color cl_l_onSecondaryContainer:   "#1A2530"
  readonly property color cl_l_tertiary:               "#B0BCB6"
  readonly property color cl_l_onTertiary:             "#1A2420"
  readonly property color cl_l_tertiaryContainer:      "#E0E8E4"
  readonly property color cl_l_onTertiaryContainer:    "#1A2420"
  readonly property color cl_l_error:                  "#BA1A1A"
  readonly property color cl_l_onError:                "#FFFFFF"
  readonly property color cl_l_errorContainer:         "#FFDAD6"
  readonly property color cl_l_onErrorContainer:       "#410002"
  readonly property color cl_l_onSurface:              "#3D3929"
  readonly property color cl_l_onSurfaceVariant:       "#5A5748"
  readonly property color cl_l_outline:                "#8A8778"
  readonly property color cl_l_outlineVariant:         "#C8C5B8"
  readonly property color cl_l_shadow:                 "#000000"
  readonly property color cl_l_scrim:                  "#000000"

  // Claude dark palette
  readonly property color cl_d_bg:                     "#000000"
  readonly property color cl_d_surface:                "#000000"
  readonly property color cl_d_surfaceDim:             "#000000"
  readonly property color cl_d_surfaceBright:          "#2A2720"
  readonly property color cl_d_surfaceContainer:       "#1A1814"
  readonly property color cl_d_surfaceContainerHigh:   "#282520"
  readonly property color cl_d_surfaceContainerHighest:"#3D3929"
  readonly property color cl_d_surfaceVariant:         "#3D3929"
  readonly property color cl_d_primary:                "#DA7756"
  readonly property color cl_d_onPrimary:              "#3D1A0A"
  readonly property color cl_d_primaryContainer:       "#8B3B22"
  readonly property color cl_d_onPrimaryContainer:     "#F5D5C8"
  readonly property color cl_d_secondary:              "#B0BCB6"
  readonly property color cl_d_onSecondary:            "#1A2520"
  readonly property color cl_d_secondaryContainer:     "#3D4A48"
  readonly property color cl_d_onSecondaryContainer:   "#D8E8E4"
  readonly property color cl_d_tertiary:               "#8492A3"
  readonly property color cl_d_onTertiary:             "#000000"
  readonly property color cl_d_tertiaryContainer:      "#2A3548"
  readonly property color cl_d_onTertiaryContainer:    "#C8D4E0"
  readonly property color cl_d_error:                  "#FFB4AB"
  readonly property color cl_d_onError:                "#690005"
  readonly property color cl_d_errorContainer:         "#93000A"
  readonly property color cl_d_onErrorContainer:       "#FFDAD6"
  readonly property color cl_d_onSurface:              "#E6E3D5"
  readonly property color cl_d_onSurfaceVariant:       "#B0BCB6"
  readonly property color cl_d_outline:                "#8A8778"
  readonly property color cl_d_outlineVariant:         "#3D3929"
  readonly property color cl_d_shadow:                 "#000000"
  readonly property color cl_d_scrim:                  "#000000"

  readonly property color l_bg: "#fff8f5"
  readonly property color l_surface: "#fff8f5"
  readonly property color l_surfaceDim: "#ebd6ca"
  readonly property color l_surfaceBright: "#fff8f5"
  readonly property color l_surfaceContainer: "#ffeade"
  readonly property color l_surfaceContainerHigh: "#f9e4d8"
  readonly property color l_surfaceContainerHighest: "#f3ded2"
  readonly property color l_surfaceVariant: "#fbddca"
  readonly property color l_primary: "#505a9a"
  readonly property color l_onPrimary: "#ffffff"
  readonly property color l_primaryContainer: "#dee0ff"
  readonly property color l_onPrimaryContainer: "#071353"
  readonly property color l_secondary: "#51643f"
  readonly property color l_onSecondary: "#ffffff"
  readonly property color l_secondaryContainer: "#d4eabb"
  readonly property color l_onSecondaryContainer: "#102003"
  readonly property color l_tertiary: "#34694a"
  readonly property color l_onTertiary: "#ffffff"
  readonly property color l_tertiaryContainer: "#b6f0c8"
  readonly property color l_onTertiaryContainer: "#002110"
  readonly property color l_error: "#ba1a1a"
  readonly property color l_onError: "#ffffff"
  readonly property color l_errorContainer: "#ffdad6"
  readonly property color l_onErrorContainer: "#410002"
  readonly property color l_onSurface: "#241912"
  readonly property color l_onSurfaceVariant: "#574335"
  readonly property color l_outline: "#8a7263"
  readonly property color l_outlineVariant: "#ddc1af"
  readonly property color l_shadow: "#000000"
  readonly property color l_scrim: "#000000"

  readonly property color d_bg: "#1b110a"
  readonly property color d_surface: "#1b110a"
  readonly property color d_surfaceDim: "#1b110a"
  readonly property color d_surfaceBright: "#43372e"
  readonly property color d_surfaceContainer: "#281d16"
  readonly property color d_surfaceContainerHigh: "#332820"
  readonly property color d_surfaceContainerHighest: "#3f322a"
  readonly property color d_surfaceVariant: "#574335"
  readonly property color d_primary: "#bbc3ff"
  readonly property color d_onPrimary: "#202a68"
  readonly property color d_primaryContainer: "#384280"
  readonly property color d_onPrimaryContainer: "#dee0ff"
  readonly property color d_secondary: "#b8cda1"
  readonly property color d_onSecondary: "#243515"
  readonly property color d_secondaryContainer: "#3a4c2a"
  readonly property color d_onSecondaryContainer: "#d4eabb"
  readonly property color d_tertiary: "#9bd3ad"
  readonly property color d_onTertiary: "#00391f"
  readonly property color d_tertiaryContainer: "#1a5033"
  readonly property color d_onTertiaryContainer: "#b6f0c8"
  readonly property color d_error: "#ffb4ab"
  readonly property color d_onError: "#690005"
  readonly property color d_errorContainer: "#93000a"
  readonly property color d_onErrorContainer: "#ffdad6"
  readonly property color d_onSurface: "#f3ded2"
  readonly property color d_onSurfaceVariant: "#ddc1af"
  readonly property color d_outline: "#a58c7c"
  readonly property color d_outlineVariant: "#574335"
  readonly property color d_shadow: "#000000"
  readonly property color d_scrim: "#000000"

  readonly property bool _cl: colorScheme === "claude"
  property color bg:                      _cl ? (darkMode ? cl_d_bg                      : cl_l_bg)                      : (darkMode ? d_bg                      : l_bg)
  property color surface:                 _cl ? (darkMode ? cl_d_surface                 : cl_l_surface)                 : (darkMode ? d_surface                 : l_surface)
  property color surfaceDim:              _cl ? (darkMode ? cl_d_surfaceDim              : cl_l_surfaceDim)              : (darkMode ? d_surfaceDim              : l_surfaceDim)
  property color surfaceBright:           _cl ? (darkMode ? cl_d_surfaceBright           : cl_l_surfaceBright)           : (darkMode ? d_surfaceBright           : l_surfaceBright)
  property color surfaceContainer:        _cl ? (darkMode ? cl_d_surfaceContainer        : cl_l_surfaceContainer)        : (darkMode ? d_surfaceContainer        : l_surfaceContainer)
  property color surfaceContainerHigh:    _cl ? (darkMode ? cl_d_surfaceContainerHigh    : cl_l_surfaceContainerHigh)    : (darkMode ? d_surfaceContainerHigh    : l_surfaceContainerHigh)
  property color surfaceContainerHighest: _cl ? (darkMode ? cl_d_surfaceContainerHighest : cl_l_surfaceContainerHighest) : (darkMode ? d_surfaceContainerHighest : l_surfaceContainerHighest)
  property color surfaceVariant:          _cl ? (darkMode ? cl_d_surfaceVariant          : cl_l_surfaceVariant)          : (darkMode ? d_surfaceVariant          : l_surfaceVariant)
  property color primary:                 _cl ? (darkMode ? cl_d_primary                 : cl_l_primary)                 : (darkMode ? d_primary                 : l_primary)
  property color fgPrimary:               _cl ? (darkMode ? cl_d_onPrimary               : cl_l_onPrimary)               : (darkMode ? d_onPrimary               : l_onPrimary)
  property color primaryContainer:        _cl ? (darkMode ? cl_d_primaryContainer        : cl_l_primaryContainer)        : (darkMode ? d_primaryContainer        : l_primaryContainer)
  property color fgPrimaryContainer:      _cl ? (darkMode ? cl_d_onPrimaryContainer      : cl_l_onPrimaryContainer)      : (darkMode ? d_onPrimaryContainer      : l_onPrimaryContainer)
  property color secondary:               _cl ? (darkMode ? cl_d_secondary               : cl_l_secondary)               : (darkMode ? d_secondary               : l_secondary)
  property color fgSecondary:             _cl ? (darkMode ? cl_d_onSecondary             : cl_l_onSecondary)             : (darkMode ? d_onSecondary             : l_onSecondary)
  property color secondaryContainer:      _cl ? (darkMode ? cl_d_secondaryContainer      : cl_l_secondaryContainer)      : (darkMode ? d_secondaryContainer      : l_secondaryContainer)
  property color fgSecondaryContainer:    _cl ? (darkMode ? cl_d_onSecondaryContainer    : cl_l_onSecondaryContainer)    : (darkMode ? d_onSecondaryContainer    : l_onSecondaryContainer)
  property color tertiary:                _cl ? (darkMode ? cl_d_tertiary                : cl_l_tertiary)                : (darkMode ? d_tertiary                : l_tertiary)
  property color fgTertiary:              _cl ? (darkMode ? cl_d_onTertiary              : cl_l_onTertiary)              : (darkMode ? d_onTertiary              : l_onTertiary)
  property color tertiaryContainer:       _cl ? (darkMode ? cl_d_tertiaryContainer       : cl_l_tertiaryContainer)       : (darkMode ? d_tertiaryContainer       : l_tertiaryContainer)
  property color fgTertiaryContainer:     _cl ? (darkMode ? cl_d_onTertiaryContainer     : cl_l_onTertiaryContainer)     : (darkMode ? d_onTertiaryContainer     : l_onTertiaryContainer)
  property color error:                   _cl ? (darkMode ? cl_d_error                   : cl_l_error)                   : (darkMode ? d_error                   : l_error)
  property color fgError:                 _cl ? (darkMode ? cl_d_onError                 : cl_l_onError)                 : (darkMode ? d_onError                 : l_onError)
  property color errorContainer:          _cl ? (darkMode ? cl_d_errorContainer          : cl_l_errorContainer)          : (darkMode ? d_errorContainer          : l_errorContainer)
  property color fgErrorContainer:        _cl ? (darkMode ? cl_d_onErrorContainer        : cl_l_onErrorContainer)        : (darkMode ? d_onErrorContainer        : l_onErrorContainer)
  property color fgSurface:               _cl ? (darkMode ? cl_d_onSurface              : cl_l_onSurface)               : (darkMode ? d_onSurface               : l_onSurface)
  property color fgSurfaceVariant:        _cl ? (darkMode ? cl_d_onSurfaceVariant        : cl_l_onSurfaceVariant)        : (darkMode ? d_onSurfaceVariant        : l_onSurfaceVariant)
  property color outline:                 _cl ? (darkMode ? cl_d_outline                 : cl_l_outline)                 : (darkMode ? d_outline                 : l_outline)
  property color outlineVariant:          _cl ? (darkMode ? cl_d_outlineVariant          : cl_l_outlineVariant)          : (darkMode ? d_outlineVariant          : l_outlineVariant)
  property color shadow:                  _cl ? (darkMode ? cl_d_shadow                  : cl_l_shadow)                  : (darkMode ? d_shadow                  : l_shadow)
  property color scrim:                   _cl ? (darkMode ? cl_d_scrim                   : cl_l_scrim)                   : (darkMode ? d_scrim                   : l_scrim)
  property color hoverOverlay: darkMode ? Qt.rgba(1, 1, 1, 0.10) : Qt.rgba(0, 0, 0, 0.06)
  property color pressOverlay: darkMode ? Qt.rgba(1, 1, 1, 0.16) : Qt.rgba(0, 0, 0, 0.10)
}
